#!/bin/sh
# Generates the credentials the demo runs on, into a gitignored .env that docker compose reads
# automatically. Run once:  ./examples/auth/gen-env.sh
#
# Both tokens are written, and they have different lifetimes. The WORKER token stays: a
# container consumes it at every start with no human present, so it has to rest somewhere a
# machine can read. The ADMIN token is there only for the FIRST start — store it wherever you
# keep credentials (`genctl config set token …`) and delete its line. Seeding is idempotent, so
# later starts do not need it, and the credential stops resting in a file compose reads and an
# environment `docker inspect` can print. specs/api-auth.md §5.
set -e
cd "$(dirname "$0")"
GENCTL=${GENCTL:-../../genctl}
[ -x "$GENCTL" ] || { echo "build genctl first: make build" >&2; exit 1; }

if [ -f .env ]; then
  echo ".env already exists — delete it to mint fresh credentials." >&2
  exit 0
fi

umask 077                        # the file holds live credentials
cat > .env <<ENV
# Generated by gen-env.sh. Gitignored. Delete and re-run to rotate.

# The evaluator reads this at every start. It stays.
WORKER_TOKEN=$("$GENCTL" token generate)

# For the FIRST start only. Store it (genctl config set token <value>), then delete this line —
# genroc has its hash and does not need the secret again. See README.md.
ADMIN_TOKEN=$("$GENCTL" token generate)
ENV
# The secrets are NOT echoed: they are in .env already, and printing them again only adds a
# copy to terminal scrollback. Where they are and what happens to them is enough — how to store
# one is the operator's business, not this script's.
echo "\nwrote examples/auth/.env (mode $(stat -f '%Lp' .env 2>/dev/null || stat -c '%a' .env))"
cat <<'NEXT'

  WORKER_TOKEN  stays — the evaluator reads it at every start.
  ADMIN_TOKEN   yours. Store it wherever you keep secrets, then delete the line after the
                first start: genroc keeps its hash and never needs the value again.
NEXT
