#!/bin/sh
# Generates the ONE credential this demo cannot mint for itself, into a gitignored .env that
# docker compose reads automatically. Run once:  ./examples/proxy/gen-env.sh
#
# Why only one, and why a file at all. A person gets their credential from the UI: log in
# through the proxy, mint a token, paste it into genctl. A WORKER cannot do that -- it starts
# with the stack, with no human present, so it needs a credential before anything is running to
# mint one from. That is the whole difference, and it is why `-seed-tokens` exists.
#
# The secret is generated HERE rather than by genroc, so it never originates inside the server
# and never reaches its logs. specs/api-auth.md §5.3.
set -e
cd "$(dirname "$0")"
GENCTL=${GENCTL:-../../genctl}
[ -x "$GENCTL" ] || { echo "build genctl first: make build" >&2; exit 1; }

if [ -f .env ]; then
  echo ".env already exists — delete it to mint a fresh credential." >&2
  exit 0
fi

umask 077                        # the file holds a live credential
cat > .env <<ENV
# Generated by gen-env.sh. Gitignored. Delete and re-run to rotate.
#
# The evaluator reads this at every start, and genroc seeds the same value so the two agree.
# Seeding is idempotent and additive: rotating means adding the new value and revoking the old,
# so a fleet rolls without a window where half of it is refused.
WORKER_TOKEN=$("$GENCTL" token generate)
ENV
# Not echoed: it is in .env already, and printing it again only adds a copy to scrollback.
echo "wrote examples/proxy/.env (mode $(stat -f '%Lp' .env 2>/dev/null || stat -c '%a' .env))"
echo "it holds the evaluator's worker token. Your own credential comes from the UI."
