// A script task: the evaluator imports this module and calls its default export with `input`.
// The parameter's type comes from the definition, generated by `genctl types`.
export default function (input: { who: string }) {
  return { greeting: `hello, ${input.who}`, at: new Date().toISOString() };
}
