// A script task: a function body, not a module. `input` is in scope; return the result.
// Its type comes from the definition, generated by `genctl types`.
export default function (input: { who: string }) {
  return { greeting: `hello, ${input.who}`, at: new Date().toISOString() };
}
