// Emits TypeScript types for process.yaml, from the schemas genroc INFERRED — so the types
// follow the definition rather than being asserted beside it.
//
// This is the CALLER's view: ProcessInput/ProcessOutput as an API client sees them over
// the wire. The script author's view - `Input`/`Output` for each `$import`ed .ts - comes
// from `genctl types` instead, and is typechecked at apply. See specs/script-tasks.md.
//
// Requires the genroc server to be running (genctl validate calls it).
//
// Outputs:
//   playground/generated/types.ts   — ProcessInput/Output + per-task Input/Output
//   playground/generated/schema.json — raw SchemaFile for inspection
//
// Usage: npm run playground:generate

import { compile } from "json-schema-to-typescript";
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

const dir = join(import.meta.dirname, "generated");
const opts = { bannerComment: "", additionalProperties: false };
const repoRoot = join(import.meta.dirname, "../..");
const PROCESS = "weather-logger";
// script.yaml travels along because weather-logger names it: validation resolves the child
// against the files on the command line before it falls back to the server.
const yamls = ["script.yaml", "process.yaml"].map((f) => join(import.meta.dirname, f));

function toPascalCase(s: string): string {
  return s
    .split(/[_-]/)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");
}

const result = spawnSync(
  "go",
  [
    "run",
    "./cmd/genctl",
    "validate",
    "--server",
    "http://localhost:8888",
    ...yamls.flatMap((f) => ["-f", f]),
  ],
  { cwd: repoRoot, encoding: "utf8" },
);

if (result.status !== 0) {
  throw new Error(`genctl validate: ${result.stderr.trim()}`);
}

type Ref = { $ref: string };
type TaskEntry = { input?: Ref; output?: Ref; action_type: string };
type SchemaFile = {
  process: string;
  process_input?: Ref;
  process_output?: Ref;
  tasks?: Record<string, TaskEntry>;
  $defs?: Record<string, object>;
};

const schemaFile = (JSON.parse(result.stdout) as SchemaFile[]).find(
  (s) => s.process === PROCESS,
);
if (!schemaFile) throw new Error(`no schemas for ${PROCESS}`);
const { process_input: processInput, process_output: processOutput, tasks = {}, $defs: defs = {} } = schemaFile;

await writeFile(join(dir, "schema.json"), JSON.stringify(schemaFile, null, 2) + "\n");
console.log("Wrote playground/generated/schema.json");

function deref(ref: Ref | undefined): Record<string, any> | undefined {
  if (!ref?.$ref) return undefined;
  return defs[ref.$ref.replace("#/$defs/", "")] as Record<string, any> | undefined;
}

// A named schema's body may point at sibling defs (a shared type, or one the engine
// hoisted), so the pool travels with every schema handed to the compiler.
function withDefs(s: object): object {
  return { ...s, $defs: defs };
}

// A script task is a child call whose input is {code, input}. Detected by that shape rather
// than declared, because nothing in the definition marks one — which is the whole design:
// the engine has no script action type. See eval-node/README.md.
function scriptInput(taskInput: Record<string, any> | undefined): object | undefined {
  const props = taskInput?.properties;
  if (props?.code?.type !== "string" || !props?.input) return undefined;
  return props.input as object;
}

const sections: string[] = [
  "// Auto-generated by playground/codegen.ts — do not edit by hand.",
  "// Re-run `npm run playground:generate` after changing process.yaml.",
  "",
];

const processIn = deref(processInput);
if (processIn) sections.push(await compile(withDefs(processIn), "ProcessInput", opts));
const processOut = deref(processOutput);
if (processOut) sections.push(await compile(withDefs(processOut), "ProcessOutput", opts));

for (const [id, task] of Object.entries(tasks)) {
  const pascal = toPascalCase(id);
  const taskInput = deref(task.input);
  const script = scriptInput(taskInput);

  // For a script task the input type is what the SCRIPT sees; `code` is the script itself
  // and typing it as `string` would say nothing.
  const input = script ?? taskInput;
  if (input) sections.push(await compile(withDefs(input), `${pascal}Input`, opts));

  const output = deref(task.output);
  if (output) sections.push(await compile(withDefs(output), `${pascal}Output`, opts));
}

// Each schema is compiled on its own with the whole $defs pool attached, so a def shared by
// two tasks (`reading` here) is emitted once per compile. Identical interfaces merge rather
// than collide, so this is legibility, not correctness — keep the FIRST of each name.
function dedupeDeclarations(source: string): string {
  const declaration = /^export (?:interface|type) (\w+)/;
  const seen = new Set<string>();
  const kept: string[] = [];
  let keeping = true;

  for (const line of source.split("\n")) {
    const m = line.match(declaration);
    if (m) keeping = !seen.has(m[1]) && (seen.add(m[1]), true);
    if (keeping) kept.push(line);
  }
  return kept.join("\n").replace(/\n{3,}/g, "\n\n");
}

await writeFile(join(dir, "types.ts"), dedupeDeclarations(sections.join("\n")));
console.log("Generated playground/generated/types.ts");
