// Generated by genroc. Do not edit - regenerate with `genctl types`.
// weather-logger / location  (/tasks/0/action/input/code)

export type geo_response = {
  country?: string;
  latitude: number;
  longitude: number;
  name: string;
};

export type Input = {
  place: string;
};

export type Output = geo_response;
