// Generated by genroc. Do not edit - regenerate with `genctl types`.
// weather-logger / reading  (/tasks/2/action/input/code)

export type geocode_output = null | {
  country?: string;
  latitude: number;
  longitude: number;
  name: string;
};

/** The clock and RNG the runner pins, so a retry re-executes identically. */
export type Ctx = { now: number; seed: string };

export type Input = {
  geo: geocode_output;
};

export type Output = {
  condition: string;
  summary: string;
  temperature_c: number;
  time: string;
};
