// Generated by genroc. Do not edit - regenerate with `genctl types`.
// weather-logger  (tasks.reading.action.input.code)

export type geo_response = {
  country?: string;
  latitude: number;
  longitude: number;
  name: string;
};
export type reading = {
  condition: string;
  summary: string;
  temperature_c: number;
  time: string;
};

export type Input = {
  geo: geo_response;
};

export type Output = reading;
