// Generated by genroc. Do not edit - regenerate with `genctl types`.
// weather-logger / reading  (/tasks/2/action/input/code)

export type location_output = geo_response;
export type reading = {
  condition: string;
  summary: string;
  temperature_c: number;
  time: string;
};
export type geo_response = {
  country?: string;
  latitude: number;
  longitude: number;
  name: string;
};

export type Input = {
  geo: location_output;
  prev: Array<reading>;
};

export type Output = Array<reading>;
