// Generated by genroc. Do not edit - regenerate with `genctl types`.
// weather-logger / summarize  (/tasks/3/action/input/code)

export type geocode_output = {
  label: null | string;
  lat: null | number;
  lon: null | number;
};
export type read_weather_output = {
  code: number;
  temperature_c: number;
  time: string;
};

/** The clock and RNG the runner pins, so a retry re-executes identically. */
export type Ctx = { now: number; seed: string };

export type Input = {
  geo: geocode_output;
  reading: read_weather_output;
};

export type Output = {
  condition: string;
  summary: string;
  temperature_c: number;
};
