package main

// The CLI reference is generated by RUNNING genctl, not by importing it: commandDocs and every
// flag set live in cmd/genctl's package main, and a flag is only registered once its command is
// already executing. The help output is the contract genctl keeps anyway. specs/docs-site.md.

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

type cliCommand struct {
	name    string
	summary string
	grammar []string // usage lines, "genctl " already stripped
	detail  string
	flags   string // the Flags: block verbatim, "" when the command has none
}

type cliGroup struct {
	title    string
	commands []cliCommand
}

// writeCLIReference emits one page per group `genctl -h` prints, so the reference and the
// terminal agree about which commands exist and how they are filed.
func writeCLIReference(dir, genctl string) error {
	groups, err := readCLIGroups(genctl)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	for i, g := range groups {
		for j := range g.commands {
			if err := readCLICommand(genctl, &g.commands[j]); err != nil {
				return err
			}
		}
		path := filepath.Join(dir, slug(g.title)+".md")
		if err := os.WriteFile(path, []byte(renderCLIGroup(g, i+1)), 0644); err != nil {
			return err
		}
		fmt.Fprintf(os.Stderr, "wrote %s (%d)\n", path, len(g.commands))
	}
	return nil
}

// readCLIGroups parses `genctl -h`, whose shape is one unindented group title followed by
// two-space-indented "name  summary" rows.
func readCLIGroups(genctl string) ([]cliGroup, error) {
	out, err := runHelp(genctl)
	if err != nil {
		return nil, err
	}
	var groups []cliGroup
	for _, line := range strings.Split(out, "\n") {
		switch {
		case strings.TrimSpace(line) == "",
			strings.HasPrefix(line, "Usage:"),
			strings.HasPrefix(line, "Environment:"):
		case !strings.HasPrefix(line, " "):
			groups = append(groups, cliGroup{title: line})
		case len(groups) > 0:
			name, summary, _ := strings.Cut(strings.TrimSpace(line), "  ")
			// The trailing block is indented like a command row but spells out invocations,
			// so a name carrying a space is that block rather than a command.
			if name == "" || strings.Contains(name, " ") {
				continue
			}
			g := &groups[len(groups)-1]
			g.commands = append(g.commands, cliCommand{name: name, summary: strings.TrimSpace(summary)})
		}
	}
	if len(groups) == 0 {
		return nil, fmt.Errorf("%s -h named no command groups; its help format changed", genctl)
	}
	return groups, nil
}

// readCLICommand fills one command from `genctl <name> -h`: the indented block under "Usage:"
// is the grammar, everything up to "Flags:" is the prose, and the rest is the flag set as the
// command's own parser prints it.
func readCLICommand(genctl string, c *cliCommand) error {
	out, err := runHelp(genctl, c.name)
	if err != nil {
		return err
	}
	body, flags, _ := strings.Cut(out, "\nFlags:\n")
	c.flags = strings.TrimRight(flags, "\n")

	lines := strings.Split(strings.TrimPrefix(body, "Usage:\n"), "\n")
	i := 0
	for ; i < len(lines) && strings.HasPrefix(lines[i], "  "); i++ {
		c.grammar = append(c.grammar, strings.TrimPrefix(strings.TrimSpace(lines[i]), "genctl "))
	}
	c.detail = strings.TrimSpace(strings.Join(lines[i:], "\n"))
	if len(c.grammar) == 0 {
		return fmt.Errorf("genctl %s -h printed no usage lines; its help format changed", c.name)
	}
	return nil
}

func runHelp(genctl string, args ...string) (string, error) {
	out, err := exec.Command(genctl, append(args, "-h")...).Output()
	if err != nil {
		return "", fmt.Errorf("run %s %s -h: %w", genctl, strings.Join(args, " "), err)
	}
	return string(out), nil
}

func renderCLIGroup(g cliGroup, order int) string {
	var names []string
	for _, c := range g.commands {
		names = append(names, "`"+c.name+"`")
	}
	b := &strings.Builder{}
	fmt.Fprintf(b, "---\ntitle: %s\ndescription: %s\norder: %d\n---\n",
		yamlString(g.title),
		yamlString(fmt.Sprintf("The genctl commands for %s: %s.", strings.ToLower(g.title), strings.Join(names, ", "))),
		order)
	fmt.Fprint(b, "\n<!-- Generated by `make docs-reference` from `genctl -h`. Do not edit. -->\n")

	for _, c := range g.commands {
		fmt.Fprintf(b, "\n## %s\n\n%s\n\n```sh\n", c.name, escapeProse(c.summary))
		for _, u := range c.grammar {
			fmt.Fprintf(b, "genctl %s\n", u)
		}
		fmt.Fprint(b, "```\n")
		if c.detail != "" {
			fmt.Fprintf(b, "\n%s\n", escapeProse(c.detail))
		}
		if c.flags != "" {
			fmt.Fprintf(b, "\n**Flags**\n\n```\n%s\n```\n", c.flags)
		}
	}
	return b.String()
}

// escapeProse protects help text from markdown: `<` would be read as raw HTML and swallow
// `tasks.<id>`, and a `**` in a glob is one re-wrap away from opening emphasis that closes on
// the next heading. Neither is escaped inside a code span, where both are already literal and
// the escape would print itself.
func escapeProse(s string) string {
	b := &strings.Builder{}
	code := false
	for _, r := range s {
		switch {
		case r == '`':
			code = !code
		case r == '<' && !code:
			b.WriteString("&lt;")
			continue
		case r == '*' && !code:
			b.WriteString("\\*")
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}

// yamlString quotes a frontmatter value. The descriptions carry a colon, which YAML reads as a
// mapping and fails the content collection's parse rather than the schema's.
func yamlString(s string) string {
	return `"` + strings.NewReplacer(`\\`, `\\\\`, `"`, `\\"`).Replace(s) + `"`
}

func slug(title string) string {
	return strings.ToLower(strings.ReplaceAll(title, " ", "-"))
}
