package main

// The error reference: what an on_error rule matches and what a reply classifies, two
// vocabularies sharing no code.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"genroc/internal/api"
	"genroc/internal/errcode"
	"genroc/internal/model"
)

// writeErrorReference writes TWO sections, definition language and HTTP: one page would invite
// a reader to try `not_found` in an on_error rule.
func writeErrorReference(definitionDir, httpDir string) error {
	for _, p := range []struct {
		dir  string
		slug string
		body string
		n    int
	}{
		{definitionDir, "errors", renderTaskErrors(), len(errcode.All())},
		{httpDir, "errors", renderAPIErrors(), len(api.ReferenceCodes())},
	} {
		if err := os.MkdirAll(p.dir, 0755); err != nil {
			return err
		}
		path := filepath.Join(p.dir, p.slug+".md")
		if err := os.WriteFile(path, []byte(p.body), 0644); err != nil {
			return err
		}
		fmt.Fprintf(os.Stderr, "wrote %s (%d)\n", path, p.n)
	}
	return nil
}

func renderTaskErrors() string {
	b := &strings.Builder{}
	fmt.Fprintf(b, "---\ntitle: %s\ndescription: %s\norder: %d\n---\n",
		yamlString("Task errors"),
		yamlString("The codes a task can fail with, and which of them an on_error rule can catch."),
		7)
	fmt.Fprint(b, "\n<!-- Generated by `make docs-reference` from internal/errcode. Do not edit. -->\n")

	fmt.Fprint(b, "\n## Catchable\n\nAn `on_error` rule matches these by code. `Reported by` is the kind of\n"+
		"task that produces the code — a rule naming one its task cannot produce is refused at\nregistration.\n")
	fmt.Fprint(b, "\n| Code | Reported by | Means |\n| --- | --- | --- |\n")
	for _, info := range errcode.Catchable(^errcode.Kind(0)) {
		fmt.Fprintf(b, "| `%s` | %s | %s |\n", info.Code, codeList(info.Kinds.Names()), cell(info.Means))
	}

	fmt.Fprint(b, "\n## HTTP status codes\n\nA fetch whose response status is not accepted fails with `http.<status>` —\n"+
		"`http.500`, `http.404`. The family is unbounded, so it has no table: match it with a\npattern, `http.5%`.\n")

	fmt.Fprint(b, "\n## Terminal\n\nThese fail the instance outright. No `on_error` rule sees one, so none can be\n"+
		"caught or retried; they are listed because every failure stores a code and these are what\n`error_code` then holds.\n")
	fmt.Fprint(b, "\n| Code | Means |\n| --- | --- |\n")
	for _, info := range errcode.Terminal() {
		fmt.Fprintf(b, "| `%s` | %s |\n", info.Code, cell(info.Means))
	}
	return b.String()
}

func renderAPIErrors() string {
	b := &strings.Builder{}
	fmt.Fprintf(b, "---\ntitle: %s\ndescription: %s\norder: %d\n---\n",
		yamlString("API errors"),
		yamlString("The classification every error reply carries, and the status each renders as."),
		8)
	fmt.Fprint(b, "\n<!-- Generated by `make docs-reference` from internal/api. Do not edit. -->\n")
	fmt.Fprint(b, "\nEvery error reply carries a `code`. It is the part a client should branch on: the HTTP\n"+
		"status is a rendering of it, and TCP and UDS callers never see a status line at all.\n")
	fmt.Fprint(b, "\n| Code | Status | Means |\n| --- | --- | --- |\n")
	for _, c := range api.ReferenceCodes() {
		fmt.Fprintf(b, "| `%s` | %d | %s |\n", c.Code, c.Status, cell(c.Means))
	}
	return b.String()
}

// codeList renders a set of names as code spans, or an em dash — a table cell left blank reads
// as a value nobody filled in.
func codeList(names []string) string {
	if len(names) == 0 {
		return "—"
	}
	return "`" + strings.Join(names, "`, `") + "`"
}

// writeStatusTable writes a fragment, not a page: no frontmatter, so the guide that imports it
// stays the one place the statuses are listed.
func writeStatusTable(path string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	b := &strings.Builder{}
	fmt.Fprint(b, "`Settled` marks a terminal state: no work moves and nothing advances out of it.\n"+
		"`Accepts a result` is whether a worker's answer to an external task is still delivered —\n"+
		"a pause suspends execution, not delivery.\n\n")
	fmt.Fprint(b, "| Status | Settled | Accepts a result | Means |\n| --- | --- | --- | --- |\n")
	for _, s := range model.Statuses() {
		fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n", s.Status, yesNo(s.Terminal), yesNo(s.Accepts), cell(s.Means))
	}
	if err := os.WriteFile(path, []byte(b.String()), 0644); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "wrote %s (%d)\n", path, len(model.Statuses()))
	return nil
}

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}
