package main

// The HTTP reference is read from the OpenAPI document this binary already builds, so the
// paths, parameters and statuses are never walked twice. api.Reference() supplies the two
// things the document has no vocabulary for -- which permission admits a call, and the example
// payloads the spec drops when it reflects zero values. specs/docs-site.md.

import (
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"genroc/internal/api"
)

var httpMethods = []string{"get", "put", "post", "delete", "patch"}

type operation struct {
	ID         string   `json:"operationId"`
	Tags       []string `json:"tags"`
	Summary    string   `json:"summary"`
	Parameters []struct {
		Name        string `json:"name"`
		In          string `json:"in"`
		Description string `json:"description"`
		Schema      struct {
			Ref  string   `json:"$ref"`
			Type any      `json:"type"`
			Enum []string `json:"enum"`
		} `json:"schema"`
	} `json:"parameters"`
	Responses map[string]struct {
		Description string `json:"description"`
	} `json:"responses"`
}

type pathItem struct {
	Servers []struct {
		URL string `json:"url"`
	} `json:"servers"`
	Methods map[string]operation `json:"-"`
}

type endpoint struct {
	method string
	url    string // the path a caller calls, base included
	op     operation
	ref    api.ReferenceAction
}

func writeHTTPReference(dir string) error {
	doc := struct {
		Servers []struct {
			URL string `json:"url"`
		} `json:"servers"`
		Paths      map[string]json.RawMessage `json:"paths"`
		Components struct {
			Schemas map[string]struct {
				Enum []string `json:"enum"`
			} `json:"schemas"`
		} `json:"components"`
	}{}
	if err := json.Unmarshal(api.Spec(), &doc); err != nil {
		return fmt.Errorf("parse the generated OpenAPI document: %w", err)
	}
	base := ""
	if len(doc.Servers) > 0 {
		base = strings.TrimSuffix(doc.Servers[0].URL, "/")
	}
	// A parameter whose type is a named one carries a $ref instead of the enum itself, and the
	// values are what a reader needs. Derived sets land here: the status filter's values come
	// from model.Status.Enum(), so the parameter names a schema rather than repeating them.
	enums := map[string][]string{}
	for name, s := range doc.Components.Schemas {
		if len(s.Enum) > 0 {
			enums["#/components/schemas/"+name] = s.Enum
		}
	}

	items := map[string]pathItem{}
	for path, raw := range doc.Paths {
		item := pathItem{Methods: map[string]operation{}}
		if err := json.Unmarshal(raw, &item); err != nil {
			return fmt.Errorf("parse path %s: %w", path, err)
		}
		var byKey map[string]json.RawMessage
		if err := json.Unmarshal(raw, &byKey); err != nil {
			return fmt.Errorf("parse path %s: %w", path, err)
		}
		for _, m := range httpMethods {
			if raw, ok := byKey[m]; ok {
				var op operation
				if err := json.Unmarshal(raw, &op); err != nil {
					return fmt.Errorf("parse %s %s: %w", m, path, err)
				}
				item.Methods[m] = op
			}
		}
		items[path] = item
	}

	// Registry order throughout: it decides which tag a page is for, the order the pages sit
	// in, and the order of the endpoints on one. Ranging the paths map instead would reorder
	// the whole reference on every run, since Go randomises it.
	var tags []string
	byTag := map[string][]endpoint{}
	for _, ref := range api.Reference() {
		item, ok := items[ref.Path]
		if !ok {
			return fmt.Errorf("%s %s is in the registry but not in the spec", ref.Method, ref.Path)
		}
		op, ok := item.Methods[strings.ToLower(ref.Method)]
		if !ok {
			continue
		}
		prefix := base
		if len(item.Servers) > 0 {
			prefix = strings.TrimSuffix(item.Servers[0].URL, "/")
		}
		tag := "Other"
		if len(op.Tags) > 0 {
			tag = op.Tags[0]
		}
		if _, seen := byTag[tag]; !seen {
			tags = append(tags, tag)
		}
		byTag[tag] = append(byTag[tag], endpoint{method: ref.Method, url: prefix + ref.Path, op: op, ref: ref})
	}
	if len(tags) == 0 {
		return fmt.Errorf("the OpenAPI document carried no tagged operations")
	}

	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	for i, tag := range tags {
		path := filepath.Join(dir, slug(tag)+".md")
		if err := os.WriteFile(path, []byte(renderHTTPTag(tag, byTag[tag], i+1, enums)), 0644); err != nil {
			return err
		}
		fmt.Fprintf(os.Stderr, "wrote %s (%d)\n", path, len(byTag[tag]))
	}
	return nil
}

func renderHTTPTag(tag string, eps []endpoint, order int, enums map[string][]string) string {
	b := &strings.Builder{}
	fmt.Fprintf(b, "---\ntitle: %s\ndescription: %s\norder: %d\n---\n",
		yamlString(tag),
		yamlString(fmt.Sprintf("The %d HTTP endpoints under %s.", len(eps), tag)),
		order)
	fmt.Fprint(b, "\n<!-- Generated by `make docs-reference` from the OpenAPI document. Do not edit. -->\n")

	for _, e := range eps {
		fmt.Fprintf(b, "\n## %s %s%s\n", e.method, e.url, swaggerLink(tag, e.op.ID))
		if e.op.Summary != "" {
			fmt.Fprintf(b, "\n%s\n", escapeProse(e.op.Summary))
		}
		fmt.Fprintf(b, "\n%s\n", permissionLine(e.ref))

		if len(e.op.Parameters) > 0 {
			fmt.Fprint(b, "\n| Parameter | In | Description |\n| --- | --- | --- |\n")
			for _, p := range e.op.Parameters {
				desc := escapeProse(p.Description)
				values := p.Schema.Enum
				if len(values) == 0 {
					values = enums[p.Schema.Ref]
				}
				if len(values) > 0 {
					// The tags are written as sentence fragments, so most carry no full stop
					// and the enum would run straight on from the last word.
					if desc != "" && !strings.HasSuffix(desc, ".") {
						desc += "."
					}
					desc = strings.TrimSpace(desc + " One of `" + strings.Join(values, "`, `") + "`.")
				}
				// A pipe inside a cell ends it, and a description is free prose.
				fmt.Fprintf(b, "| `%s` | %s | %s |\n", p.Name, p.In, strings.ReplaceAll(desc, "|", `\|`))
			}
		}
		if e.ref.Request != nil {
			fmt.Fprintf(b, "\n**Request**\n\n```json\n%s\n```\n", e.ref.Request)
		}
		if e.ref.Response != nil {
			fmt.Fprintf(b, "\n**Response**\n\n```json\n%s\n```\n", e.ref.Response)
		}
		if codes := failureStatuses(e.op); len(codes) > 0 {
			fmt.Fprintf(b, "\nFails with `%s`.\n", strings.Join(codes, "`, `"))
		}
	}
	return b.String()
}

// Empty, with its label drawn by CSS: text here would land in the heading's id and TOC entry.
// The href is relative to /reference/rest-api/<tag>/ so an archived build links its own explorer;
// docs/scripts/check-links.mjs resolves the fragment.
func swaggerLink(tag, operationID string) string {
	href := "../../../swagger/index.html#/" + url.PathEscape(tag) + "/" + url.PathEscape(operationID)
	return `<a class="swagger-link" href="` + href + `" target="_blank" rel="noopener" aria-label="Open in Swagger UI"></a>`
}

// permissionLine says what a caller needs. Empty permissions is the registry's fail-closed
// default rather than a gap, so it must read as a statement and not as a blank.
func permissionLine(ref api.ReferenceAction) string {
	switch {
	case ref.Open:
		return "Needs no credential."
	case len(ref.Permissions) == 0:
		return "Requires the `admin` permission."
	case len(ref.Permissions) == 1:
		return fmt.Sprintf("Requires the `%s` permission (or `admin`).", ref.Permissions[0])
	}
	return fmt.Sprintf("Requires any of `%s` (or `admin`).", strings.Join(ref.Permissions, "`, `"))
}

func failureStatuses(op operation) []string {
	var out []string
	for code := range op.Responses {
		if code >= "400" {
			out = append(out, code)
		}
	}
	sort.Strings(out)
	return out
}
