package main

// The server reference RUNS genroc, as the CLI reference runs genctl: its flags live in package
// main. Grouping is the one thing help text cannot carry, so serverGroups must name every flag.

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

type serverFlag struct {
	name, kind, def, usage string
}

var serverGroups = []struct {
	title, intro string
	flags        []string
}{
	{"Listening", "Where the API is served. An empty `--http` runs a worker-only node.", []string{"http", "pprof"}},
	{"Database", "SQLite by default; `--pg` switches to PostgreSQL.", []string{"db", "pg", "pg-max-open-conns"}},
	{"Durability", "What is flushed to disk before a write is acknowledged.",
		[]string{"durability", "sqlite-synchronous", "sqlite-fullfsync", "pg-commit-delay"}},
	{"Authentication", "Off by default (`--auth none`). Machines use tokens; people reach the API through genroc-ui.",
		[]string{"auth", "bootstrap-token", "seed-tokens", "seed-tokens-file",
			"jwt-secret-file", "jwt-issuer", "jwt-audience", "jwt-leeway"}},
	{"Engine", "How instances are claimed and advanced.",
		[]string{"poll", "max-concurrent", "lease-duration", "lease-renew-interval", "immediate-retries"}},
	{"Logging", "Console output and the per-instance audit trail.",
		[]string{"log", "log-mode", "log-payloads", "log-payload-bytes", "log-retention"}},
	{"Objects", "Large values kept out of the instance row.", []string{"object-grace"}},
	{"Other", "", []string{"version"}},
}

func writeServerReference(dir, genroc string) error {
	flags, err := readServerFlags(genroc)
	if err != nil {
		return err
	}
	token, err := readTokenUsage(genroc)
	if err != nil {
		return err
	}
	page, err := renderServerReference(flags, token)
	if err != nil {
		return err
	}
	path := filepath.Join(dir, "server.md")
	if err := os.WriteFile(path, []byte(page), 0644); err != nil {
		return err
	}
	fmt.Fprintf(os.Stderr, "wrote %s (%d flags)\n", path, len(flags))
	return nil
}

var (
	flagHeader = regexp.MustCompile(`^  --?(\S+)(?: (\S+))?$`)
	flagDef    = regexp.MustCompile(` \(default (.+)\)$`)
)

// readServerFlags parses genroc's flag listing: "  --name type" then tab-indented usage lines.
func readServerFlags(genroc string) ([]serverFlag, error) {
	// -h exits non-zero on some Go versions; the listing is what matters.
	out, _ := exec.Command(genroc, "-h").CombinedOutput()
	var flags []serverFlag
	for _, line := range strings.Split(string(out), "\n") {
		if m := flagHeader.FindStringSubmatch(line); m != nil {
			flags = append(flags, serverFlag{name: m[1], kind: m[2]})
			continue
		}
		if usage, ok := strings.CutPrefix(line, "    \t"); ok && len(flags) > 0 {
			f := &flags[len(flags)-1]
			f.usage = strings.TrimSpace(f.usage + " " + usage)
		}
	}
	if len(flags) == 0 {
		return nil, fmt.Errorf("no flags parsed from %s -h:\n%s", genroc, out)
	}
	for i := range flags {
		if m := flagDef.FindStringSubmatch(flags[i].usage); m != nil {
			flags[i].def = strings.Trim(m[1], `"`)
			flags[i].usage = strings.TrimSuffix(flags[i].usage, m[0])
		}
	}
	return flags, nil
}

// readTokenUsage takes the usage `genroc token` prints when run bare (it exits 2 doing so).
func readTokenUsage(genroc string) (string, error) {
	out, _ := exec.Command(genroc, "token").CombinedOutput()
	s := strings.TrimSpace(string(out))
	if !strings.Contains(s, "genroc token create") {
		return "", fmt.Errorf("genroc token printed no usage:\n%s", s)
	}
	return s, nil
}

// renderServerReference refuses a flag no group names, and a group naming a flag genroc lacks:
// either way the page would silently disagree with the binary.
func renderServerReference(flags []serverFlag, tokenUsage string) (string, error) {
	byName := make(map[string]serverFlag, len(flags))
	for _, f := range flags {
		byName[f.name] = f
	}
	grouped := map[string]bool{}
	for _, g := range serverGroups {
		for _, n := range g.flags {
			if _, ok := byName[n]; !ok {
				return "", fmt.Errorf("server reference group %q names --%s, which genroc no longer has", g.title, n)
			}
			grouped[n] = true
		}
	}
	for _, f := range flags {
		if !grouped[f.name] {
			return "", fmt.Errorf("genroc flag --%s is in no group in cmd/genrocspec/serverref.go", f.name)
		}
	}

	b := &strings.Builder{}
	fmt.Fprintf(b, "---\ntitle: Server\ndescription: %s\norder: 4\n---\n",
		yamlString("Every flag of the genroc server, and the genroc token subcommand."))
	fmt.Fprint(b, "\n<!-- Generated by `make docs-reference` from `genroc -h`. Do not edit. -->\n")
	fmt.Fprint(b, "\nFlags are written `--name value` or `--name=value`. Where a flag names an environment variable,"+
		" the variable is read when the flag is not given.\n")
	for _, g := range serverGroups {
		fmt.Fprintf(b, "\n## %s\n", g.title)
		if g.intro != "" {
			fmt.Fprintf(b, "\n%s\n", g.intro)
		}
		for _, n := range g.flags {
			f := byName[n]
			kind := f.kind
			if kind == "" {
				kind = "boolean"
			}
			meta := "`" + kind + "`"
			if f.def != "" {
				meta += " · default `" + f.def + "`"
			}
			fmt.Fprintf(b, "\n### --%s\n\n%s\n\n%s\n", f.name, meta, escapeProse(f.usage))
		}
	}
	fmt.Fprintf(b, "\n## genroc token\n\n```\n%s\n```\n", tokenUsage)
	return b.String(), nil
}
